name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./md-to-html

    steps:
    - uses: actions/checkout@v4

    - name: Set up the tag name
      id: vars
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci

    - name: Zip directory
      run: |
        zip -r ../markdown-it-${{ env.TAG_NAME }}.zip .
        ls -l ../
        echo Deploying artifact ../markdown-it-${{ env.TAG_NAME }}.zip
