name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.repository == 'Sage-Bionetworks/synapse-markdown-it-lambda'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./md-to-html

    steps:
    - uses: actions/checkout@v4

    - name: Set up the tag name
      id: vars
      run: echo "TAG_NAME=${GITHUB_REF##*/}" | sed 's/\./-/g' >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci

    - name: Zip directory
      run: |
        zip -r ../markdown-it-${{ env.TAG_NAME }}.zip .

    - name: Setup JF
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_USER: ${{ secrets.PLATFORM_ARTIFACTORY_USER }}
        JF_PASSWORD: ${{ secrets.PLATFORM_ARTIFACTORY_PWD }}

    -  run: |
        echo Deploying artifact ../markdown-it-${{ env.TAG_NAME }}.zip
        jf rt ping
