name: deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ARTIFACT_NAME: markdown-it-${{ github.ref_name }}.zip
    defaults:
      run:
        working-directory: ./md-to-html

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-node@v7
      with:
        node-version: 24.x

    - run: npm ci --omit=dev

    - name: Zip directory
      run: |
        zip -r ../$ARTIFACT_NAME .

    - name: Create GitHub Release and upload asset
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref_name }}
        name: synapse-markdown-it-lambda ${{ github.ref_name }}
        body: Release of synapse-markdown-it-lambda version ${{ github.ref_name }}
        files: ${{ env.ARTIFACT_NAME }}

    - name: Artifactory
      run: |
        JFROG_URL=https://sagebionetworks.jfrog.io/artifactory/lambda-artifacts/org/sagebionetworks/markdown-it
        curl --fail --show-error --silent -u ${{ secrets.JFROG_CREDS }} -T ../$ARTIFACT_NAME $JFROG_URL/$ARTIFACT_NAME
